version: '3'

services:
  web:
    build: api
    command: bash -c "python manage.py collectstatic --noinput && python manage.py migrate && gunicorn server.wsgi -b 0.0.0.0:8000"
    ports:
      - "8000:8000"